# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 970b936394a9014f85daa9573763c57e0b0eb407ce03720e657f8b92c3ec022c29a9073d9e543537767e754e89482ba7624b320bab2a0a3be0fef63fd63be487

test:
  secret_key_base: 4ae0942f52100abf05667582c48d61a051586edd449b7629c21a987098321262f2f7fc9f94725af49670d370a7858218fbddf05f540e0a1f08aa97a825095614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
